# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        carre: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [200, 200] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        reduc:
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]
                # name our first filter set "my_heighten_filter"
        my_heighten_filter:
            filters:

                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 60

        # name our second filter set "my_widen_filter"
        my_widen_filter:
            filters:

                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 32x26px using "widen" option
                    widen: 32

        # name our second filter set "my_increase_filter"
        my_increase_filter:
            filters:

                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 60x50px, using "increase" option
                    increase: 10

        # name our second filter set "my_scale_filter"
        my_scale_filter:
            filters:

                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 125x100px using "scale" option
                    scale: 2.5