<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container06JoQDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container06JoQDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container06JoQDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container06JoQDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container06JoQDx\App_KernelDevDebugContainer([
    'container.build_hash' => '06JoQDx',
    'container.build_id' => '115c9453',
    'container.build_time' => 1586243758,
], __DIR__.\DIRECTORY_SEPARATOR.'Container06JoQDx');
